### ISSUE TITLE
broken package?

### ISSUE THREAD

**Issue by 93578237** [federicotdn/aiorsmq#1]
Hi, thx for your work.
So i tried installing through pip, but got only dist-info, not the package.

**Comment by federicotdn** [comment]
Hi! Thanks for checking on this, I've made a mistake when packaging the repo. I'll get to it this week.

**Comment by 93578237** [comment]
@federicotdn could you also add wheels?

**Comment by federicotdn** [comment]
0.1.2 should now work correctly! Also added wheel packages.
